spring.application.name=Backend-Wellnest
spring.data.mongodb.uri=
server.port=${PORT:5000}
jwt.secret=${JWT_SECRET:fitness_square_super_secret_key_2026}
# Enable static file serving
spring.web.resources.static-locations=classpath:/static/

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.default-encoding=UTF-8

GOOGLE_CLIENT_ID=
# Suppress invalid cookie warnings (e.g. from Google g_state cookie)
logging.level.org.apache.tomcat.util.http.parser.Cookie=ERROR
